### PR TITLE
camera behaviour changed, about window up to date, vbo bug corrected

### PR DESCRIPTION
**Pull request by renaud-lebrun**
I changed the behaviour of the camera as you requested : 
- I added a button (with a little camera on it).
  => When you have loaded Meshes and click on that button, the centre of rotation of the camera becomes that of the centre of mass of all opened objects. The grid becomes drawn "blue" to remind users that the centre of rotation is not 0,0,0
- when you click again on that button, the "normal" camera behaviour (rotation around 0,0,0) starts again, and the grid is drawn again orange.
- I also updated the about window to make your name appear + mention the Github repository
- I also corrected a draw bug : only when VBO was activated, when moving the position of a selected object using the roller and slider controls (that is : not using the mouse), the objects where not displayed at their current location in space until the control was released.

Can you tell me if it works as needed ?

### CODE REVIEW

**Comment by zarquon42b** [comment]
This is just aweseome. Merged. 
Maybe make this the default view if "keep object in native coordinate system" is selected.

**Comment by renaud-lebrun** [comment]
Then probably the best thing is to save "g_mode_cam_centre_of_mass" in the MeshTools.ini file ?

**Comment by zarquon42b** [comment]
Probably. 
What I thought was, If you do not want to translate your data to the origin, you want to focus the camera to your data.

**Comment by renaud-lebrun** [comment]
Ok : 
- translation of data to the origin is achieved (as it was) using the option : "Show->General options-> Behaviour when opening surfaces : Object poisition : Move object centre of mass at 0,0,0
- focus of the camera to the data is achieved when the "camera button" is pressed (and grid is then dislplayed as blue). => This behaviour is not saved in the .ini file

**Comment by renaud-lebrun** [comment]
is now saved in the .ini file.

**Pull request merged**
